apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinqoreactwebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coinqoreactwebapp
  template:
    metadata:
      labels:
        app: coinqoreactwebapp
    spec:
      containers:
      - name: coinqoreactwebapp
        image: coinqoacr.azurecr.io/coinqoreactwebapp:v1
        resources:
          requests:
            cpu: 1024m
            memory: 2048Mi
          limits:
            cpu: 2048m
            memory: 4096Mi
      imagePullSecrets:
        - name: mfo

 
