apiVersion: apps/v1
kind: Deployment
metadata:
  name: kriptoyonetim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kriptoyonetim
  template:
    metadata:
      labels:
        app: kriptoyonetim
    spec:
      containers:
      - name: kriptoyonetim
        image: criptoacr.azurecr.io/kriptoyonetim:v1
        resources:
          requests:
            cpu: 1024m
            memory: 2048Mi
          limits:
            cpu: 2048m
            memory: 4096Mi
      imagePullSecrets:
        - name: test

 
