apiVersion: apps/v1
kind: Deployment
metadata:
  name: criptoyonetim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: criptoyonetim
  template:
    metadata:
      labels:
        app: criptoyonetim
    spec:
      containers:
      - name: criptoyonetim
        image: kriptoyonetimacr.azurecr.io/criptoyonetim:v1
        resources:
          requests:
            cpu: 1024m
            memory: 2048Mi
          limits:
            cpu: 2048m
            memory: 4096Mi
      imagePullSecrets:
        - name: cripto-registry

 
