apiVersion: apps/v1
kind: Deployment
metadata:
  name: criptoyonetim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: criptoyonetim
  template:
    metadata:
      labels:
        app: criptoyonetim
    spec:
      containers:
      - name: criptoyonetim
        image: finanssehiracr.azurecr.io/criptoyonetim:v1
        resources:
          requests:
            cpu: 500m
            memory: 600Mi
          limits:
            cpu: 700m
            memory: 800Mi
      imagePullSecrets:
        - name: finans-registry


 
