apiVersion: apps/v1
kind: Deployment
metadata:
  name: criptoyonetim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: criptoyonetim
  template:
    metadata:
      labels:
        app: criptoyonetim
    spec:
      containers:
      - name: criptoyonetim
        image: kriptoyonetimacr.azurecr.io/coinqolanding:v1
        resources:
          requests:
            cpu: 200m
            memory: 250Mi
          limits:
            cpu: 500m
            memory: 500Mi
      imagePullSecrets:
        - name: coinqo-registy

 
