apiVersion: apps/v1
kind: Deployment
metadata:
  name: criptoyonetimreact
spec:
  replicas: 1
  selector:
    matchLabels:
      app: criptoyonetimreact
  template:
    metadata:
      labels:
        app: criptoyonetimreact
    spec:
      containers:
      - name: criptoyonetim
        image: criptoacr.azurecr.io/criptoyonetimreact:v1
        resources:
          requests:
            cpu: 1024m
            memory: 2048Mi
          limits:
            cpu: 2048m
            memory: 4096Mi
      imagePullSecrets:
        - name: cripto-registry

 
