# Base image
FROM node:14

# Set working directory
WORKDIR /app

# Copy package.json and yarn.lock
COPY package*.json yarn.lock ./

# Install dependencies
RUN yarn install

# Copy application files
COPY . .

# Build the application
RUN yarn build

# Set the startup command
CMD [ "yarn", "start" ]
